name: wildfire-discord-bot
region: nyc
services:
- name: wildfire-bot
  github:
    repo: chriswingler/wildfire-cli
    branch: main
  run_command: cd /app && python src/main.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  source_dir: /
  http_port: 8080