blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Ideas & Discussions
    url: https://github.com/chriswingler/wildfire-cli/discussions
    about: Share ideas, ask questions, or discuss the project
  - name: 📚 Documentation & Setup Help
    url: https://github.com/chriswingler/wildfire-cli/wiki
    about: Get help with setup, installation, or project documentation
  - name: 🔥 Wildfire Management Resources
    url: https://www.nifc.gov/
    about: Learn more about real wildfire incident command and management