name: 🎯 User Story
description: Create a new user story for feature development
title: "[USER STORY] "
labels: ["user-story"]
assignees: []
body:
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a [user type], I want [functionality] so that [benefit]
      placeholder: |
        As an incident commander, I want to see realistic fire behavior reports so that I can make informed tactical decisions.
    validations:
      required: true

  - type: dropdown
    id: epic
    attributes:
      label: Epic
      description: Which epic does this story belong to?
      options:
        - 🔥 Fire Engine (Core Simulation)
        - 🎮 Game Loop (Gameplay Mechanics)
        - 🖥️ UI/UX (User Interface)
        - 📋 Content (Game Content)
        - 🧪 Testing (Quality Assurance)
    validations:
      required: true

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      description: Estimated effort (Fibonacci sequence)
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "21"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Business priority level
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Specific conditions that must be met for this story to be considered complete
      placeholder: |
        - [ ] Condition 1 is met
        - [ ] Condition 2 is met
        - [ ] Condition 3 is met
    validations:
      required: true

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: General completion criteria (leave blank to use project defaults)
      placeholder: |
        - [ ] Code implemented and reviewed
        - [ ] Unit tests written and passing
        - [ ] Integration tests passing
        - [ ] Documentation updated
        - [ ] Acceptance criteria verified
    validations:
      required: false

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Implementation hints, constraints, or dependencies
      placeholder: Any technical considerations, API requirements, or architectural notes
    validations:
      required: false