name: 🧪 Test Basic Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Basic Test
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo test
        run: echo "✅ Basic workflow is working!"
        
      - name: Test GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"